// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgGvs6H6uHAA5HzaLpXbGH0JgMfte-F-A',
    appId: '1:422402787915:web:792c484e2c81e683d85bce',
    messagingSenderId: '422402787915',
    projectId: 'gear-92794',
    authDomain: 'gear-92794.firebaseapp.com',
    storageBucket: 'gear-92794.appspot.com',
    measurementId: 'G-QCLVK8TV0Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1CQNscODWczpgzJM7WThIncF5PYZ3o6M',
    appId: '1:422402787915:android:6f33977169d7c555d85bce',
    messagingSenderId: '422402787915',
    projectId: 'gear-92794',
    storageBucket: 'gear-92794.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYh_U2OA7TEEzAFwraTa6Szx0WfKgtOUI',
    appId: '1:422402787915:ios:f65e597c28ea56aad85bce',
    messagingSenderId: '422402787915',
    projectId: 'gear-92794',
    storageBucket: 'gear-92794.appspot.com',
    iosBundleId: 'com.example.emartApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYh_U2OA7TEEzAFwraTa6Szx0WfKgtOUI',
    appId: '1:422402787915:ios:f65e597c28ea56aad85bce',
    messagingSenderId: '422402787915',
    projectId: 'gear-92794',
    storageBucket: 'gear-92794.appspot.com',
    iosBundleId: 'com.example.emartApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgGvs6H6uHAA5HzaLpXbGH0JgMfte-F-A',
    appId: '1:422402787915:web:ac4373221d1a93b2d85bce',
    messagingSenderId: '422402787915',
    projectId: 'gear-92794',
    authDomain: 'gear-92794.firebaseapp.com',
    storageBucket: 'gear-92794.appspot.com',
    measurementId: 'G-XX0J4W8F41',
  );

}